export const BASE_URL = 'http://127.0.1.1:8080/api'; //'http://75e17217.ngrok.io/api'; //

/* Auth */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/* Notifications */
export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_HIDE = 'SNACKBAR_HIDE';

/* Desk Actions */
export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';
export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAIL = 'REMOVE_TODO_FAIL';
export const REORDER_TODO_REQUEST = 'REORDER_TODO_REQUEST';
export const REORDER_TODO_SUCCESS = 'REORDER_TODO_SUCCESS';
export const REORDER_TODO_FAIL = 'REORDER_TODO_FAIL';
export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_FAIL = 'ADD_LIST_FAIL';
export const REMOVE_LIST_REQUEST = 'REMOVE_LIST_REQUEST';
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS';
export const REMOVE_LIST_FAIL = 'REMOVE_LIST_FAIL';
export const RENAME_LIST_REQUEST = 'RENAME_LIST_REQUEST';
export const RENAME_LIST_SUCCESS = 'RENAME_LIST_SUCCESS';
export const RENAME_LIST_FAIL = 'RENAME_LIST_FAIL';
export const REORDER_LIST_REQUEST = 'REORDER_LIST_REQUEST';
export const REORDER_LIST_SUCCESS = 'REORDER_LIST_SUCCESS';
export const REORDER_LIST_FAIL = 'REORDER_LIST_FAIL';

/* Item Modal Actions*/
export const ITEM_MODAL_SHOW = 'ITEM_MODAL_SHOW';
export const ITEM_MODAL_HIDE = 'ITEM_MODAL_HIDE';
export const LIST_MODAL_SHOW = 'LIST_MODAL_SHOW';
export const LIST_MODAL_HIDE = 'LIST_MODAL_HIDE';
export const CHANGE_ITEM_REQUEST = 'CHANGE_ITEM_REQUEST';
export const CHANGE_ITEM_SUCCESS = 'CHANGE_ITEM_SUCCESS';
export const CHANGE_ITEM_FAIL = 'CHANGE_ITEM_FAIL';
export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
